# Generated by Django 3.2.5 on 2021-07-05 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Squad_Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', multiselectfield.db.fields.MultiSelectField(choices=[('sn', 'sniper'), ('ca', 'camper'), ('ru', 'rusher'), ('co', 'cover')], max_length=8)),
                ('server', models.CharField(choices=[('EU', 'europe'), ('AS', 'asia'), ('KO', 'korea'), ('AF', 'africa'), ('US', 'america')], max_length=2)),
                ('min_rank', models.CharField(max_length=30)),
                ('min_kd', models.FloatField(max_length=5)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('apply', models.ManyToManyField(blank=True, null=True, related_name='requested', to=settings.AUTH_USER_MODEL, verbose_name='متقاضیان')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
            ],
            options={
                'verbose_name': 'پست اسکواد',
                'verbose_name_plural': 'پست اسکواد ها',
            },
        ),
    ]
