# Generated by Django 3.2.5 on 2021-07-05 14:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squad_article',
            name='apply',
            field=models.ManyToManyField(blank=True, related_name='requested', to=settings.AUTH_USER_MODEL, verbose_name='متقاضیان'),
        ),
    ]
