# Generated by Django 3.2.5 on 2021-07-06 09:55

from django.conf import settings
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0002_alter_squad_article_apply'),
    ]

    operations = [
        migrations.AddField(
            model_name='squad_article',
            name='accepted',
            field=models.ManyToManyField(blank=True, related_name='accepted', to=settings.AUTH_USER_MODEL, verbose_name='متقاضیان قبول شده'),
        ),
        migrations.AddField(
            model_name='squad_article',
            name='min_level',
            field=models.FloatField(default=3, max_length=5, verbose_name='حداقل level'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='squad_article',
            name='rejected',
            field=models.ManyToManyField(blank=True, related_name='rejected', to=settings.AUTH_USER_MODEL, verbose_name='متقاضیان رد شده'),
        ),
        migrations.AlterField(
            model_name='squad_article',
            name='min_kd',
            field=models.FloatField(max_length=5, verbose_name='حداقل kd'),
        ),
        migrations.AlterField(
            model_name='squad_article',
            name='min_rank',
            field=models.CharField(max_length=30, verbose_name='حداقل رنک'),
        ),
        migrations.AlterField(
            model_name='squad_article',
            name='role',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('sn', 'sniper'), ('ca', 'camper'), ('ru', 'rusher'), ('co', 'cover')], max_length=8, verbose_name='نقش'),
        ),
        migrations.AlterField(
            model_name='squad_article',
            name='server',
            field=models.CharField(choices=[('EU', 'europe'), ('AS', 'asia'), ('KO', 'korea'), ('AF', 'africa'), ('US', 'america')], max_length=2, verbose_name='سرور'),
        ),
    ]
