# Generated by Django 3.2.5 on 2021-07-26 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_alter_account_detail_rank'),
        ('article', '0004_alter_squad_article_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squad_article',
            name='min_rank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='squad_article', to='user.rank'),
        ),
    ]
