# Generated by Django 3.2.5 on 2021-07-28 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20210728_1511'),
        ('article', '0005_alter_squad_article_min_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squad_article',
            name='min_rank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squad_article', to='user.rank'),
        ),
    ]
