# Generated by Django 3.2.5 on 2021-07-30 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_alter_squad_article_min_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='squad_article',
            name='min_time_to_play',
            field=models.IntegerField(default=0, max_length=2, verbose_name='حداقل تایم بازی در روز'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='squad_article',
            name='min_level',
            field=models.IntegerField(max_length=5, verbose_name='حداقل level'),
        ),
    ]
