# Generated by Django 3.2.5 on 2021-08-01 10:27

from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_auto_20210801_1457'),
        ('article', '0009_newsletter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'verbose_name': 'خبرنامه', 'verbose_name_plural': 'خبرنامه ها'},
        ),
        migrations.AlterField(
            model_name='squad_article',
            name='min_kd',
            field=models.FloatField(max_length=5, validators=[user.models.validate_min], verbose_name='حداقل kd'),
        ),
        migrations.AlterField(
            model_name='squad_article',
            name='min_level',
            field=models.IntegerField(validators=[user.models.validate_min], verbose_name='حداقل level'),
        ),
        migrations.AlterField(
            model_name='squad_article',
            name='min_rank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squad_article', to='user.rank', verbose_name='حداقل رنک'),
        ),
        migrations.AlterField(
            model_name='squad_article',
            name='min_time_to_play',
            field=models.IntegerField(validators=[user.models.validate_min], verbose_name='حداقل تایم بازی در روز(ساعت)'),
        ),
    ]
