# Generated by Django 3.2.5 on 2021-07-04 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210703_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='account_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(max_length=30)),
                ('start_season', models.IntegerField()),
                ('role', models.CharField(choices=[('sn', 'sniper'), ('ca', 'camper'), ('ru', 'rusher'), ('co', 'cover')], max_length=2)),
                ('server', models.CharField(choices=[('EU', 'europe'), ('AS', 'asia'), ('KO', 'korea'), ('AF', 'africa'), ('US', 'america')], max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='acc_detail',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='user.account_detail'),
        ),
    ]
