# Generated by Django 3.2.5 on 2021-07-04 10:34

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210704_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_detail',
            name='role',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('sn', 'sniper'), ('ca', 'camper'), ('ru', 'rusher'), ('co', 'cover')], max_length=8),
        ),
        migrations.AlterField(
            model_name='account_detail',
            name='server',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('EU', 'europe'), ('AS', 'asia'), ('KO', 'korea'), ('AF', 'africa'), ('US', 'america')], max_length=10),
        ),
    ]
