# Generated by Django 3.2.5 on 2021-07-04 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_account_detail_player'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account_detail',
            options={'verbose_name': 'اطلاعات اکانت', 'verbose_name_plural': 'اطلاعات اکانت ها'},
        ),
        migrations.AlterField(
            model_name='account_detail',
            name='server',
            field=models.CharField(choices=[('EU', 'europe'), ('AS', 'asia'), ('KO', 'korea'), ('AF', 'africa'), ('US', 'america')], max_length=2),
        ),
    ]
