# Generated by Django 3.2.5 on 2021-07-05 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20210705_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_detail',
            name='id_game',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='account_detail',
            name='kd',
            field=models.FloatField(default=None, max_length=5),
        ),
        migrations.AddField(
            model_name='account_detail',
            name='level',
            field=models.IntegerField(default=None, validators=[user.models.validate_min]),
        ),
        migrations.AddField(
            model_name='account_detail',
            name='username_game',
            field=models.CharField(default=None, max_length=60),
        ),
        migrations.AlterField(
            model_name='account_detail',
            name='role',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('sn', 'sniper'), ('ca', 'camper'), ('ru', 'rusher'), ('co', 'cover')], max_length=8),
        ),
        migrations.AlterField(
            model_name='account_detail',
            name='server',
            field=models.CharField(choices=[('EU', 'europe'), ('AS', 'asia'), ('KO', 'korea'), ('AF', 'africa'), ('US', 'america')], max_length=2),
        ),
        migrations.AlterField(
            model_name='account_detail',
            name='start_season',
            field=models.IntegerField(validators=[user.models.validate_min]),
        ),
        migrations.CreateModel(
            name='Squad_Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', multiselectfield.db.fields.MultiSelectField(choices=[('sn', 'sniper'), ('ca', 'camper'), ('ru', 'rusher'), ('co', 'cover')], max_length=8)),
                ('server', models.CharField(choices=[('EU', 'europe'), ('AS', 'asia'), ('KO', 'korea'), ('AF', 'africa'), ('US', 'america')], max_length=2)),
                ('min_rank', models.CharField(max_length=30)),
                ('min_kd', models.FloatField(max_length=5)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('apply', models.ManyToManyField(related_name='requested', to=settings.AUTH_USER_MODEL, verbose_name='متقاضیان')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
            ],
        ),
    ]
