# Generated by Django 3.2.5 on 2021-07-05 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20210705_1439'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Squad_Article',
        ),
    ]
