# Generated by Django 3.2.5 on 2021-07-06 09:55

from django.db import migrations, models
import multiselectfield.db.fields
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_delete_squad_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_detail',
            name='id_game',
            field=models.CharField(default=None, max_length=20, verbose_name='ایدی شما در بازی'),
        ),
        migrations.AlterField(
            model_name='account_detail',
            name='kd',
            field=models.FloatField(default=None, max_length=5, verbose_name='kd شما'),
        ),
        migrations.AlterField(
            model_name='account_detail',
            name='level',
            field=models.IntegerField(default=None, validators=[user.models.validate_min], verbose_name='لول شما'),
        ),
        migrations.AlterField(
            model_name='account_detail',
            name='rank',
            field=models.CharField(max_length=30, verbose_name='رنک بازی'),
        ),
        migrations.AlterField(
            model_name='account_detail',
            name='role',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('sn', 'sniper'), ('ca', 'camper'), ('ru', 'rusher'), ('co', 'cover')], max_length=8, verbose_name='نقش'),
        ),
        migrations.AlterField(
            model_name='account_detail',
            name='server',
            field=models.CharField(choices=[('EU', 'europe'), ('AS', 'asia'), ('KO', 'korea'), ('AF', 'africa'), ('US', 'america')], max_length=2, verbose_name='سرور'),
        ),
        migrations.AlterField(
            model_name='account_detail',
            name='start_season',
            field=models.IntegerField(validators=[user.models.validate_min], verbose_name='سیزن شروع بازی'),
        ),
        migrations.AlterField(
            model_name='account_detail',
            name='username_game',
            field=models.CharField(default=None, max_length=60, verbose_name='یوزرنیم شما در بازی'),
        ),
    ]
