# Generated by Django 3.2.5 on 2021-07-07 07:08

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20210706_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_detail',
            name='time_to_play',
            field=models.IntegerField(default=1, validators=[user.models.validate_min], verbose_name='میزان ساعت بازی در روز'),
            preserve_default=False,
        ),
    ]
