# Generated by Django 3.2.5 on 2021-07-26 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_account_detail_time_to_play'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='اسم رنک')),
                ('position', models.IntegerField(unique=True)),
            ],
            options={
                'verbose_name': 'رنک',
                'verbose_name_plural': 'رنک ها',
            },
        ),
    ]
