# Generated by Django 3.2.5 on 2021-07-26 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_detail',
            name='rank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='acc_detail', to='user.rank'),
        ),
    ]
