# Generated by Django 3.2.5 on 2021-07-28 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_alter_account_detail_rank'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rank',
            options={'ordering': ['position'], 'verbose_name': 'رنک', 'verbose_name_plural': 'رنک ها'},
        ),
        migrations.AlterField(
            model_name='account_detail',
            name='rank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acc_detail', to='user.rank'),
        ),
    ]
