# Generated by Django 3.2.5 on 2021-07-30 09:46

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20210728_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_detail',
            name='role',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('sn', 'sniper'), ('ca', 'camper'), ('ru', 'rusher'), ('co', 'cover')], max_length=11, verbose_name='نقش'),
        ),
    ]
