# Generated by Django 3.2.5 on 2021-08-01 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_alter_account_detail_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_notif',
            field=models.BooleanField(default=False, verbose_name='دریافت ایمیل'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_sms',
            field=models.BooleanField(default=False, verbose_name='دریافت sms'),
        ),
    ]
